ALTER TABLE warehouses ADD COLUMN deleted_at DATETIME DEFAULT NULL COMMENT '删除时间';
ALTER TABLE inbound_orders ADD COLUMN deleted_at DATETIME DEFAULT NULL COMMENT '删除时间';
ALTER TABLE inbound_order_items ADD COLUMN deleted_at DATETIME DEFAULT NULL COMMENT '删除时间';
ALTER TABLE pick_orders ADD COLUMN deleted_at DATETIME DEFAULT NULL COMMENT '删除时间';
ALTER TABLE pick_order_items ADD COLUMN deleted_at DATETIME DEFAULT NULL COMMENT '删除时间';
ALTER TABLE shipping_orders ADD COLUMN deleted_at DATETIME DEFAULT NULL COMMENT '删除时间';
ALTER TABLE shipping_trackings ADD COLUMN deleted_at DATETIME DEFAULT NULL COMMENT '删除时间';
