brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 注册到 namesrv 的 IP，部署时改为服务器公网 IP
brokerIP1 = 127.0.0.1
