import { defineConfig } from 'umi';

export default defineConfig({
  title: '宝贝小答',
  metas: [
    { name: 'description', content: '宝贝小答 - 智能问答与社交社区平台，分享生活好物，发现精彩内容' },
    { name: 'keywords', content: '宝贝小答,社区,问答,好物推荐,生活分享,社交平台' },
    { name: 'theme-color', content: '#00D4FF' },
    { name: 'mobile-web-app-capable', content: 'yes' },
    { name: 'apple-mobile-web-app-status-bar-style', content: 'black-translucent' },
    { name: 'format-detection', content: 'telephone=no' },
    { rel: 'manifest', href: '/manifest.json' },
  ],
  links: [
    { rel: 'icon', href: '/favicon.ico' },
    { rel: 'apple-touch-icon', href: '/icons/icon-192.png' },
  ],
  extraBabelPlugins: [],
  routes: [
    {
      path: '/',
      component: '@/layouts/UserLayout',
      routes: [
        { path: '/', component: '@/pages/Home' },
        { path: '/products', component: '@/pages/ProductList' },
        { path: '/products/:id', component: '@/pages/ProductDetail' },
        { path: '/search', component: '@/pages/Search' },
        { path: '/cart', component: '@/pages/Cart' },
        { path: '/wishlist', component: '@/pages/Wishlist' },
        { path: '/checkout', component: '@/pages/Checkout' },
        { path: '/orders', component: '@/pages/OrderList' },
        { path: '/orders/:id', component: '@/pages/OrderDetail' },
        { path: '/payment/:id', component: '@/pages/Payment' },
        { path: '/shop/seckill', component: '@/pages/Seckill' },
        { path: '/shop/group-buy', component: '@/pages/GroupBuy' },
        { path: '/shop/coupons', component: '@/pages/Coupons' },
        { path: '/live', component: '@/pages/LiveList' },
        { path: '/live/:roomId', component: '@/pages/LiveRoom' },
        { path: '/ai-chat', component: '@/pages/AiChat' },
        { path: '/post/:id', component: '@/pages/PostDetail' },
        { path: '/publish', component: '@/pages/Publish' },
        { path: '/messages', component: '@/pages/Messages' },
        { path: '/chat', component: '@/pages/Chat' },
        { path: '/chat/:conversationId', component: '@/pages/Chat' },
        { path: '/profile', component: '@/pages/UserCenter' },
        { path: '/settings', component: '@/pages/Settings' },
        { path: '/user/:id', component: '@/pages/UserProfile' },
        { path: '/topic/:id', component: '@/pages/TopicDetail' },
        { path: '/user/:id/following', component: '@/pages/Following' },
        { path: '/collections', component: '@/pages/Collections' },
        { path: '/wish', component: '@/pages/WishHome' },
        { path: '/wish/list', component: '@/pages/WishSquare' },
        { path: '/wish/create', component: '@/pages/WishCreate' },
        { path: '/wish/my', component: '@/pages/MyWishes' },
        { path: '/wish/badges', component: '@/pages/BadgeWall' },
        { path: '/wish/tree', component: '@/pages/WorldTree3D' },
        { path: '/wish/:id/tree-hole', component: '@/pages/TreeHole' },
        { path: '/wish/:id/fulfillment', component: '@/pages/WishFulfillment' },
        { path: '/wish/:id', component: '@/pages/WishDetail' },
      ],
    },
    {
      path: '/admin',
      component: '@/layouts/AdminLayout',
      routes: [
        { path: '/admin', redirect: '/admin/dashboard' },
        { path: '/admin/login', component: '@/pages/admin/Login' },
        { path: '/admin/dashboard', component: '@/pages/admin/Dashboard' },
        { path: '/admin/system/users', component: '@/pages/admin/system/Users' },
        { path: '/admin/system/roles', component: '@/pages/admin/system/Roles' },
        { path: '/admin/system/menus', component: '@/pages/admin/system/Menus' },
        { path: '/admin/system/depts', component: '@/pages/admin/system/Depts' },
        { path: '/admin/system/posts', component: '@/pages/admin/system/Posts' },
        { path: '/admin/system/dict', component: '@/pages/admin/system/Dict' },
        { path: '/admin/system/config', component: '@/pages/admin/system/Config' },
        { path: '/admin/system/notices', component: '@/pages/admin/system/Notices' },
        { path: '/admin/system/oper-log', component: '@/pages/admin/system/OperLog' },
        { path: '/admin/system/login-log', component: '@/pages/admin/system/LoginLog' },
        { path: '/admin/business/products', component: '@/pages/admin/business/Products' },
        { path: '/admin/business/categories', component: '@/pages/admin/business/Categories' },
        { path: '/admin/business/orders', component: '@/pages/admin/business/Orders' },
        { path: '/admin/business/members', component: '@/pages/admin/business/Members' },
        { path: '/admin/business/coupons', component: '@/pages/admin/business/Coupons' },
        { path: '/admin/business/seckill', component: '@/pages/admin/business/Seckill' },
        { path: '/admin/business/cart', component: '@/pages/admin/business/Cart' },
        { path: '/admin/business/reviews', component: '@/pages/admin/business/Reviews' },
        { path: '/admin/business/inventory', component: '@/pages/admin/business/Inventory' },
        { path: '/admin/business/payments', component: '@/pages/admin/business/Payments' },
        { path: '/admin/business/notifications', component: '@/pages/admin/business/Notifications' },
        { path: '/admin/business/group-activity', component: '@/pages/admin/business/GroupActivity' },
        { path: '/admin/business/tiered-promotion', component: '@/pages/admin/business/TieredPromotion' },
        { path: '/admin/business/live', component: '@/pages/admin/business/Live' },
        { path: '/admin/business/wms', component: '@/pages/admin/business/Wms' },
        { path: '/admin/business/blacklist', component: '@/pages/admin/business/Blacklist' },
        { path: '/admin/business/ai', component: '@/pages/admin/business/Ai' },
        { path: '/admin/business/brands', component: '@/pages/admin/business/Brands' },
        { path: '/admin/business/risk-records', component: '@/pages/admin/business/RiskRecords' },
        { path: '/admin/business/risk-rules', component: '@/pages/admin/business/RiskRules' },
        { path: '/admin/business/shipping', component: '@/pages/admin/business/Shipping' },
        { path: '/admin/business/warehouses', component: '@/pages/admin/business/Warehouses' },
        { path: '/admin/business/file-upload', component: '@/pages/admin/business/FileUpload' },
        { path: '/admin/business/wish-categories', component: '@/pages/admin/business/WishCategories' },
        { path: '/admin/business/wish-interactions', component: '@/pages/admin/business/WishInteractions' },
        { path: '/admin/business/wish-comments', component: '@/pages/admin/business/WishComments' },
        { path: '/admin/business/wish-badges', component: '@/pages/admin/business/WishBadges' },
        { path: '/admin/community/posts', component: '@/pages/admin/community/Posts' },
        { path: '/admin/community/comments', component: '@/pages/admin/community/Comments' },
        { path: '/admin/community/tags', component: '@/pages/admin/community/Tags' },
        { path: '/admin/community/reports', component: '@/pages/admin/community/Reports' },
        { path: '/admin/community/badges', component: '@/pages/admin/community/Badges' },
        { path: '/admin/community/growth', component: '@/pages/admin/community/Growth' },
        { path: '/admin/community/notifications', component: '@/pages/admin/community/Notifications' },
        { path: '/admin/community/review', component: '@/pages/admin/community/Review' },
        { path: '/admin/community/chat', component: '@/pages/admin/community/Chat' },
        { path: '/admin/monitor/job', component: '@/pages/admin/monitor/Job' },
        { path: '/admin/monitor/server', component: '@/pages/admin/monitor/Server' },
        { path: '/admin/monitor/cache', component: '@/pages/admin/monitor/Cache' },
        { path: '/admin/monitor/online', component: '@/pages/admin/monitor/Online' },
        { path: '/admin/tool/gen', component: '@/pages/admin/tool/Gen' },
      ],
    },
    { path: '/login', component: '@/pages/Login' },
    { path: '/register', component: '@/pages/Register' },
    { path: '*', component: '@/pages/NotFound' },
  ],
  proxy: {
    '/api': {
      target: 'http://129.204.152.168:8090',
      changeOrigin: true,
      onProxyReq: (proxyReq) => {
        // 移除 Origin/Referer 头，避免 Gateway CORS 校验拦截非 localhost 来源的请求
        proxyReq.removeHeader('origin')
        proxyReq.removeHeader('referer')
      },
    },
    '/ws': {
      target: 'ws://129.204.152.168:8090',
      ws: true,
      changeOrigin: true,
    },
  },
  npmClient: 'npm',
  hash: true,
  jsMinifier: 'terser',
  cssMinifier: 'cssnano',
});
