global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mall-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8090']

  - job_name: 'mall-auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9001']

  - job_name: 'mall-user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9002']

  - job_name: 'mall-product'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9003']

  - job_name: 'mall-payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9004']

  - job_name: 'mall-order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9005']

  - job_name: 'mall-inventory'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9006']

  - job_name: 'mall-coupon'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9007']

  - job_name: 'mall-risk'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9008']

  - job_name: 'mall-seckill'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9011']

  - job_name: 'mall-cart'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9010']

  - job_name: 'mall-ai'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9013']

  - job_name: 'mall-marketing'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9014']

  - job_name: 'mall-live'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9015']

  - job_name: 'mall-notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9012']

  - job_name: 'mall-file'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9030']

  - job_name: 'mall-admin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9020']

  - job_name: 'mall-community'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9021']

  - job_name: 'mall-wms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9017']

  - job_name: 'mall-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9040']

  - job_name: 'mall-gen'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9050']
