export default [
  {
    path: '/',
    component: './layouts/UserLayout',
    routes: [
      { path: '/', component: './Home' },
      { path: '/products', component: './ProductList' },
      { path: '/products/:id', component: './ProductDetail' },
      { path: '/search', component: './Search' },
      { path: '/cart', component: './Cart' },
      { path: '/wishlist', component: './Wishlist' },
      { path: '/checkout', component: './Checkout' },
      { path: '/orders', component: './OrderList' },
      { path: '/orders/:id', component: './OrderDetail' },
      { path: '/payment/:id', component: './Payment' },
      { path: '/shop/seckill', component: './Seckill' },
      { path: '/shop/group-buy', component: './GroupBuy' },
      { path: '/shop/coupons', component: './Coupons' },
      { path: '/live', component: './LiveList' },
      { path: '/live/:roomId', component: './LiveRoom' },
      { path: '/ai-chat', component: './AiChat' },
      { path: '/post/:id', component: './PostDetail' },
      { path: '/publish', component: './Publish' },
      { path: '/messages', component: './Messages' },
      { path: '/chat', component: './Chat' },
      { path: '/chat/:conversationId', component: './Chat' },
      { path: '/profile', component: './UserCenter' },
      { path: '/settings', component: './Settings' },
      { path: '/user/:id', component: './UserProfile' },
      { path: '/topic/:id', component: './TopicDetail' },
      { path: '/user/:id/following', component: './Following' },
      { path: '/collections', component: './Collections' },
      { path: '/wish', component: './WishHome' },
      { path: '/wish/create', component: './WishCreate' },
      { path: '/wish/my', component: './MyWishes' },
      { path: '/wish/list', component: './WishSquare' },
      { path: '/wish/:id/tree-hole', component: './TreeHole' },
      { path: '/wish/:id', component: './WishDetail' },
      { path: '/login', component: './Login' },
      { path: '/register', component: './Register' },
    ],
  },
  {
    path: '/admin',
    component: './layouts/AdminLayout',
    routes: [
      { path: '/admin/login', component: './admin/Login' },
      { path: '/admin', redirect: '/admin/dashboard' },
      { path: '/admin/dashboard', component: './admin/Dashboard' },
      { path: '/admin/system/users', component: './admin/system/Users' },
      { path: '/admin/system/roles', component: './admin/system/Roles' },
      { path: '/admin/system/menus', component: './admin/system/Menus' },
      { path: '/admin/system/depts', component: './admin/system/Depts' },
      { path: '/admin/system/posts', component: './admin/system/Posts' },
      { path: '/admin/system/dict', component: './admin/system/Dict' },
      { path: '/admin/system/config', component: './admin/system/Config' },
      { path: '/admin/system/notices', component: './admin/system/Notices' },
      { path: '/admin/system/oper-log', component: './admin/system/OperLog' },
      { path: '/admin/system/login-log', component: './admin/system/LoginLog' },
      { path: '/admin/business/products', component: './admin/business/Products' },
      { path: '/admin/business/categories', component: './admin/business/Categories' },
      { path: '/admin/business/orders', component: './admin/business/Orders' },
      { path: '/admin/business/members', component: './admin/business/Members' },
      { path: '/admin/business/coupons', component: './admin/business/Coupons' },
      { path: '/admin/business/seckill', component: './admin/business/Seckill' },
      { path: '/admin/business/cart', component: './admin/business/Cart' },
      { path: '/admin/business/reviews', component: './admin/business/Reviews' },
      { path: '/admin/business/inventory', component: './admin/business/Inventory' },
      { path: '/admin/business/payments', component: './admin/business/Payments' },
      { path: '/admin/business/notifications', component: './admin/business/Notifications' },
      { path: '/admin/business/group-activity', component: './admin/business/GroupActivity' },
      { path: '/admin/business/tiered-promotion', component: './admin/business/TieredPromotion' },
      { path: '/admin/business/live', component: './admin/business/Live' },
      { path: '/admin/business/wms', component: './admin/business/Wms' },
      { path: '/admin/business/blacklist', component: './admin/business/Blacklist' },
      { path: '/admin/business/ai', component: './admin/business/Ai' },
      { path: '/admin/business/brands', component: './admin/business/Brands' },
      { path: '/admin/business/risk-records', component: './admin/business/RiskRecords' },
      { path: '/admin/business/risk-rules', component: './admin/business/RiskRules' },
      { path: '/admin/business/shipping', component: './admin/business/Shipping' },
      { path: '/admin/business/warehouses', component: './admin/business/Warehouses' },
      { path: '/admin/business/file-upload', component: './admin/business/FileUpload' },
      { path: '/admin/business/wishes', component: './admin/business/Wishes' },
      { path: '/admin/business/wish-categories', component: './admin/business/WishCategories' },
      { path: '/admin/business/wish-interactions', component: './admin/business/WishInteractions' },
      { path: '/admin/business/wish-comments', component: './admin/business/WishComments' },
      { path: '/admin/community/posts', component: './admin/community/Posts' },
      { path: '/admin/community/review', component: './admin/community/Review' },
      { path: '/admin/community/comments', component: './admin/community/Comments' },
      { path: '/admin/community/tags', component: './admin/community/Tags' },
      { path: '/admin/community/reports', component: './admin/community/Reports' },
      { path: '/admin/community/badges', component: './admin/community/Badges' },
      { path: '/admin/community/growth', component: './admin/community/Growth' },
      { path: '/admin/community/notifications', component: './admin/community/Notifications' },
      { path: '/admin/community/chat', component: './admin/community/Chat' },
      { path: '/admin/monitor/job', component: './admin/monitor/Job' },
      { path: '/admin/monitor/server', component: './admin/monitor/Server' },
      { path: '/admin/monitor/cache', component: './admin/monitor/Cache' },
      { path: '/admin/monitor/online', component: './admin/monitor/Online' },
      { path: '/admin/tool/gen', component: './admin/tool/Gen' },
    ],
  },
  { path: '*', component: './NotFound' },
]
